// <auto-generated />
using System;
using ABP_test_task.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ABP_test_task.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902230714_RemoveCustomerData")]
    partial class RemoveCustomerData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ABP_test_task.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationHours")
                        .HasColumnType("integer")
                        .HasColumnName("duration_hours");

                    b.Property<int>("HallId")
                        .HasColumnType("integer")
                        .HasColumnName("hall_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_price");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("HallId")
                        .HasDatabaseName("ix_bookings_hall_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("ABP_test_task.Entities.BookingService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<decimal>("PriceAtBooking")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price_at_booking");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.HasKey("Id")
                        .HasName("pk_booking_services");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_booking_services_booking_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_booking_services_service_id");

                    b.ToTable("booking_services", (string)null);
                });

            modelBuilder.Entity("ABP_test_task.Entities.ConferenceHall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePricePerHour")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_price_per_hour");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_halls");

                    b.ToTable("halls", (string)null);
                });

            modelBuilder.Entity("ABP_test_task.Entities.HallService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HallId")
                        .HasColumnType("integer")
                        .HasColumnName("hall_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.HasKey("Id")
                        .HasName("pk_hall_services");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_hall_services_service_id");

                    b.HasIndex("HallId", "ServiceId")
                        .IsUnique()
                        .HasDatabaseName("ix_hall_services_hall_id_service_id");

                    b.ToTable("hall_services", (string)null);
                });

            modelBuilder.Entity("ABP_test_task.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("ABP_test_task.Entities.Booking", b =>
                {
                    b.HasOne("ABP_test_task.Entities.ConferenceHall", "Hall")
                        .WithMany("Bookings")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_halls_hall_id");

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("ABP_test_task.Entities.BookingService", b =>
                {
                    b.HasOne("ABP_test_task.Entities.Booking", "Booking")
                        .WithMany("BookingServices")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_services_bookings_booking_id");

                    b.HasOne("ABP_test_task.Entities.Service", "Service")
                        .WithMany("BookingServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_services_services_service_id");

                    b.Navigation("Booking");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ABP_test_task.Entities.HallService", b =>
                {
                    b.HasOne("ABP_test_task.Entities.ConferenceHall", "Hall")
                        .WithMany("HallServices")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hall_services_halls_hall_id");

                    b.HasOne("ABP_test_task.Entities.Service", "Service")
                        .WithMany("HallServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hall_services_services_service_id");

                    b.Navigation("Hall");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ABP_test_task.Entities.Booking", b =>
                {
                    b.Navigation("BookingServices");
                });

            modelBuilder.Entity("ABP_test_task.Entities.ConferenceHall", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("HallServices");
                });

            modelBuilder.Entity("ABP_test_task.Entities.Service", b =>
                {
                    b.Navigation("BookingServices");

                    b.Navigation("HallServices");
                });
#pragma warning restore 612, 618
        }
    }
}
